name: Deploy to Firebase

on:
  push:
    branches: [main]
    paths:
      - 'functions/**'
      - 'firebase.json'
      - 'firestore.rules'
      - 'firestore.indexes.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Create Service Account Key
        run: |
          mkdir -p functions/config
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > functions/config/serviceAccountKey.json

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions,firestore --token "$FIREBASE_TOKEN" --non-interactive
